### ISSUE TITLE
Hi Ed!  Joel Dubiner here...

### ISSUE THREAD

**Issue by jdubiner** [vielmetti/vacuum#11]
Hi Ed,

I noticed that you are using github for your newsletter.  I haven't checked to see if you are already doing so, but if you aren't, check out:

https://pages.github.com/

it's friendly, and you can host with with a nice looking UI.

Another option would be an AWS S3 bucket in HTTP hosting mode.

I'd be happy to help set up either for you.

-- Joel Dubiner
joel@dubiner.com

**Comment by vielmetti** [comment]
Thanks Joel!

I've used `hugo` before to generate a static HTML website from source Markdown files. It's a pretty nice toolset and is fairly friendly to deal with if you pick a good theme. http://gohugo.io .

What I thought I'd do is write some more (and collect up some more old writing) and then see what organizing structure worked the best. I think it's probably too early to do a full website design until I have at least a dozen newsletters put together (and for me to be convinced that I will keep up that writing pace!)
